### ISSUE TITLE
many joysticks in one teensy

### ISSUE THREAD

**Issue by vasilyman** [zlittell/MSF-XINPUT#25]
Can many joysticks work in one teensy?

**Comment by zlittell** [comment]
unfortunately only one joystick can work per teensy.  This is because the
device is limited to imitating the xbox controllers usb descriptors and
there isn't any wiggle room.  If you deviate and even leave out some of the
filler they use in their descriptor, the driver just won't work with the
device.

**Comment by swilliams-dev** [comment]
Lurker here, what about emulating the usb wireless adapter?
http://tattiebogle.net/index.php/ProjectRoot/Xbox360Controller/WirelessUsbInfo
